-------------------------------------------------------------------------------
Test set: in.tamilselvan.doc4you.TestCreateUser
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.152 s <<< FAILURE! - in in.tamilselvan.doc4you.TestCreateUser
in.tamilselvan.doc4you.TestCreateUser.testCreateUserWithValidataInput()  Time elapsed: 0.139 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.RuntimeException
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.tamilselvan.doc4you.TestCreateUser.testCreateUserWithValidataInput(TestCreateUser.java:22)
Caused by: java.lang.RuntimeException
	at in.tamilselvan.doc4you.dao.UserDAO.create(UserDAO.java:103)
	at in.tamilselvan.doc4you.service.UserService.create(UserService.java:31)
	at in.tamilselvan.doc4you.TestCreateUser.lambda$testCreateUserWithValidataInput$0(TestCreateUser.java:23)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

